channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=24.0
- pip:
  - mlflow==2.11.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - matplotlib==3.7.2
  - numpy==1.23.2
  - packaging==23.1
  - pandas==2.0.3
  - plotly==5.18.0
  - prophet==1.1.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
name: mlflow-env
